### ISSUE TITLE
i got error    self._parser.Parse(data, 0) xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 222

### ISSUE THREAD

**Issue by dido97** [myles/python-wp#15]
when i am trying use this  from wordpress import WordPress
i get error    
self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 222

**Comment by myles** [comment]
Do you have anymore information? This is a little vague.

**Comment by dido97** [comment]
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from wordpress import WordPress
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\wordpress.py", line 144, in <module>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\wordpress.py", line 144, in <module>
    xmlrpc_object.post_article(wp_url,wp_username,wp_password,articleTitle, articleCategories, articleContent, articleTags,ariclePhotoUrl)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\wordpress.py", line 95, in post_article
    client = Client(self.wpUrl,self.wpUserName,self.wpPassword)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\site-packages\wordpress_xmlrpc\base.py", line 24, in __init__
    self.supported_methods = self.server.mt.supportedMethods()
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1452, in __request
    verbose=self.__verbose
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1336, in parse_response
    p.feed(data)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 439, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 222

**Comment by myles** [comment]
@dido97 you aren't using my library. Mine is using JSON and that one is using XMLRPC.

**Comment by dido97** [comment]
>>> wp = WordPress('http://www.mysite.com')
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    wp = WordPress('http://www.mysite.com')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_wp-1.0.0-py3.7.egg\wordpress\api.py", line 23, in __init__
    self.url = self._get_wp_api_url(url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_wp-1.0.0-py3.7.egg\wordpress\api.py", line 55, in _get_wp_api_url
    raise Exception
Exception
